title = "Wherd"
baseURL = "https://www.wherd.dev/"
languageCode = "en-US"
defaultContentLanguage = "nen"
defaultContentLang = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
enableGitInfo=true

footnoteReturnLinkContents = "↩"

[markup]
[markup.goldmark]
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true

[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5
